name: Code Check

on:
  push:
    branches-ignore: ["production"]
  pull_request:

jobs:
  lint:
    runs-on: ["self-hosted", "Windows", "X64"]
    steps:
    - name: Allow PowerShell Scripts
      shell: cmd
      run: powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force"

    - name: Pull commits
      uses: actions/checkout@v4

    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.1"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Lint with flake8
      run: python -m flake8 --ignore=C812,W503,C815,C816,W504

  typecheck:
    runs-on: ["self-hosted", "Windows", "X64"]
    steps:
    - name: Allow PowerShell Scripts
      shell: cmd
      run: powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force"

    - name: Pull commits
      uses: actions/checkout@v4

    - name: Set up Python 3.13.1
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.1"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Type check with mypy
      run: python -m mypy --no-color-output ./gov24 --disable-error-code "annotation-unchecked"
